catalog/urls.py
from django.conf.urls import url
from . import views

app_name='catalog'                              #per distinguere questi url/views da altre app (video 21 )


urlpatterns = [
    url(r'^catalog/$', views.itemlist, name='Itemlist'),                                  #Mostra la lista degli item, tutti oppure solo quelli filtrati
    url(r'^details/(?P<item_id>[0-9]+)/$', views.itemdetail, name="Itemdetail"),          #Porta alla pagina del dettaglio di un preciso item
    url(r'^search/$',views.search,name="Search")                                           #Pagina di ricerca avanzata
]

checkout/urls.py
from django.conf.urls import url
from . import views

app_name='checkout'

urlpatterns = [
    url(r'^$', views.cart, name='Cart'),                                                                                #Mostra carrello
    url(r'^additem/(?P<item_id>[0-9]+)/$',views.additem,name='Additem'),                                                #Mostra la pagina per aggiungere un oggetto al carrello
    url(r'^deleteitem/(?P<item_id>[0-9]+)/$',views.deleteitem,name='Deleteitem'),                    #Elimina un oggetto dal carrello
    url(r'^payment/(?P<cart_id>[0-9]+)$',views.payment,name="Payment"),                                                 #Gestione pagamenti
    url(r'^retrieve/(?P<item_id>[0-9]+)$',views.retrieve,name="Retrieve"),                                              #View per download oggetti
    url(r'^placeorder/(?P<cart_id>[0-9]+)$',views.placeorder,name="Placeorder")                                         #Conferma l'acquisto
]

home/urls.py
from django.conf.urls import url
from . import views

app_name='home'                              #per distinguere questi url/views da altre app (video 21 )


urlpatterns = [
    url(r'^$', views.home, name='Home'),

]

ilquadernodellostudente/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url('admin/', admin.site.urls),
    url('catalog/', include('catalog.urls')),
    url('users/', include('users.urls')),
    url('',include('home.urls'))  ,
    url('checkout/',include('checkout.urls'))#home page
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from . import views

app_name='users'


urlpatterns = [
    url(r'^$', views.login_view, name='Login'),                                                                         #Pagina di login
    url(r'^(?P<user_id>[0-9]+|None|)/$',views.profile,name='Profile'),                                                  #Mostra il profilo utente
    url(r'^editdata/$',views.editdata,name="Editdata"),                                                                 #Pagina di modifica dati profilo
    url(r'^editimage/$',views.editimage,name="Editimage"),                                                              #Pagina di modifica immagine
    url(r'^editpassword/$',views.editpassword,name="Editpassword"),                                                     #Pagina di cambio password
    url(r'^purchaselist/$',views.purchaselist,name="Purchaselist"),                                                     #Lista degli oggetti acquistati dall'utente
    url(r'^logout/$',views.logout_view,name='Logout'),                                                                  #Pagina di logout
    url(r'^signup/$',views.signup,name='Signup'),                                                                       #Pagina di registrazione
    url(r'^create/$',views.create,name="Create"),                                                                       #Pagina per creazione di nuove inserzioni
    url(r'^selectitem/$',views.selectitem,name="Selectitem"),                                                           #Pagina che mostra gli oggetti su cui è possibile apportare modifiche/eliminare/recensire
    url(r'^deleteitem/(?P<item_id>[0-9]+)/$', views.deleteitem, name="Deleteitem"),                                     #Pagina per eliminazione oggetto
    url(r'^edititem/(?P<item_id>[0-9]+)/$', views.edititem, name="Edititem"),                                           #Pagina per modifica dati oggetto
    url(r'^review/(?P<item_id>[0-9]+)/$', views.review, name="Review"),                                                 #Pagina che permette di lasciare un voto agli oggetti


]

catalog/models.py
from django.db import models
from django.core.validators import FileExtensionValidator,MinValueValidator,MaxValueValidator
from users.models import Profile



# Create your models here.




class Item(models.Model):               #Modello dell'oggetto
    SCHOOL_LEVEL = (
        ('M', 'Medie'),
        ('S', 'Superiori'),
        ('U', 'Università'),
    )
    vendor=models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,verbose_name="Venditore")               #Colui che vende l'oggetto
    name = models.CharField(max_length=50,verbose_name="Nome")
    description=models.TextField(max_length=1000,verbose_name="Descrizione dell'oggetto")
    subject=models.CharField(max_length=30,verbose_name="Materia/disciplina")                                #materia
    school_level=models.CharField(max_length=1,choices=SCHOOL_LEVEL,verbose_name="Livello scolastico")                  #media, superiore, università
    is_visible=models.BooleanField(default=True)                                                          #Se l'utente ha cancellato l'oggetto dalla vendita, non è più visibile nel catalogo e quindi non più acquistabile
    vote=models.DecimalField(max_digits=2,decimal_places=1,default=0,validators=[MinValueValidator(0,'Il voto minimo non può essere minore di 0'),MaxValueValidator(5,"Il voto massimo non può essere più di 5")],verbose_name="Voto")
    price= models.DecimalField(max_digits=6, decimal_places=2,validators=[MinValueValidator(2,'Il prezzo minimo non può essere minore di 2€')],verbose_name="Prezzo di vendita")    #Validator per prezzo minimo >= 2
    image=models.FileField(verbose_name="Immagine di anteprima",help_text='Si consiglia fortemente l\'uso di immagini di dimensioni 400x400 px',upload_to='item/preview',validators=[FileExtensionValidator(['png','jpg','jpeg'],'Formato non valido. Inserisci una immagine con uno dei seguenti formati: jpg,jpeg,png')])       #Validator per estensione
    file=models.FileField(help_text="E' obbligatorio l'uso del formato pdf.",upload_to='item/files',validators=[FileExtensionValidator(['pdf'],'Formato non valido. Inserisci un file in formato pdf')])            #Validator per estensione

    def __str__(self):
        return self.name

class HaveItem(models.Model):                   #Associa ogni utente alla lista di oggetti che ha comprato, in modo da permettergli di scaricarli in futuro
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    itemspurchased = models.ManyToManyField(Item, blank=True)               #Lista oggetti comprati

    def __str__(self):
        return "Lista oggetti comprati da:" + self.profile.user.username

class ReviewsObject(models.Model):              #Associa ogni utente alla lista degli oggetti che ha recensito, per controlare che ogni oggetto venga recensito solo una volta per utente
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    reviewed_object = models.ManyToManyField(Item, blank=True)  # Lista oggetti recensiti

    def __str__(self):
        return "Lista oggetti recensiti da:" + self.profile.user.username

home/models.py
from django.db import models

# Create your models here.

catalog/forms.py
from django import forms


class SearchForm(forms.Form):            #Form per ricerca oggetti
    SCHOOL_LEVEL = (
        ('M', 'Medie'),
        ('S', 'Superiori'),
        ('U', 'Università'),
    )
    name=forms.CharField(max_length=50,required=False,label="Nome dell'oggetto")
    subject=forms.CharField(max_length=50,required=False,label="Materia/Disciplina")
    school_level=forms.ChoiceField(choices=SCHOOL_LEVEL,required=False,widget=forms.RadioSelect,label="Livello scolastico")

catalog/views.py
from django.shortcuts import render, get_object_or_404  # scorciatoie per template e 404
from .models import Item, ReviewsObject
from users.models import Profile
from .forms import SearchForm
from checkout.models import Cart


def itemlist(request):  # mostra la lista degli oggetti
    user = request.user  # Utente loggato, lo passiamo al template per mostrare i bottoni corretti
    n_reviews = []  # Lista che contiene il numero di reviews per ogni oggetto
    vote_list = []  # Lista che contiene il voto di ogni oggetto
    item_list = Item.objects.filter(is_visible=True).order_by(
        'price')  # Lista di tutti gli oggetti nel catalogo ordinati per prezzo, eventualmente da filtrare
    if request.method == 'GET':  # Se la pagina viene invocata per la prima volta o dopo aver eseguito una ricerca con la barra di ricerca
        name = request.GET.get("q")
        if name:  # Se effettivamente è stata eseguita una ricerca
            item_list = item_list.filter(name__icontains=name)
        for item in item_list:
            n_reviews.append(ReviewsObject.objects.filter(
                reviewed_object__name=item.name).count())  # Per ogni oggetto ricaviamo il numero di recensioni
            vote_list.append(round(item.vote * 2) / 2)  # Portiamo il voto al più vicino valore utile (2.5,3,3.5.....))
        return render(request, "catalog.html",
                      {'item_list': item_list, 'user': user, 'reviews': n_reviews[::-1], 'vote_list': vote_list[::-1]})

    else:  # Richiesta fatta dal form(metodo post) nella pagina di ricerca avanzata
        form = SearchForm(request.POST)
        if form.is_valid():  # Ricaviamo i dati e filtriamo gli oggetti
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            school_level = form.cleaned_data['school_level']
            item_list = item_list.filter(name__icontains=name)
            item_list = item_list.filter(subject__icontains=subject)
            item_list = item_list.filter(school_level__icontains=school_level)
            for item in item_list:
                n_reviews.append(ReviewsObject.objects.filter(
                    reviewed_object__name=item.name).count())  # Per ogni oggetto ricaviamo il numero di recensioni
                vote_list.append(round(item.vote * 2) / 2)
        return render(request, "catalog.html",
                      {'item_list': item_list, 'user': user, 'reviews': n_reviews[::-1], 'vote_list': vote_list[::-1]})


def itemdetail(request, item_id):  # mostra la pagina di dettaglio di un preciso oggetto
    item = get_object_or_404(Item, pk=item_id, is_visible=True)
    user = request.user
    n_reviews = (ReviewsObject.objects.filter(reviewed_object__name=item.name).count())
    vote = round(item.vote * 2) / 2
    if user.is_authenticated:  # Se l'utente è loggato controlliamo che l'oggetto non skia già nel suo carrello
        profile = Profile.objects.get(user=user)
        cart = Cart.objects.get_or_create(owner=profile)[0]  # Prende il carrello dell'utente o lo crea
        items = cart.get_cart_items()  # Ottiene tutti gli item nel carrello
        for entry in items:
            if entry == item:  # L'oggetto è già nel carrello
                msg = "Questo oggetto è già nel tuo carrello!"
                return render(request, 'detail.html',
                              {'user': user, 'item': item, 'reviews': n_reviews, 'vote_list': vote,
                               'msg_already_in_cart': msg})
    return render(request, "detail.html", {'item': item, 'user': user, 'reviews': n_reviews, 'vote_list': vote})


def search(request):  # Mostra il form della ricerca e lo spedisce alla wiew itemlist
    user = request.user
    if request.method == 'GET':
        form = SearchForm()
        return render(request, "search.html", {'form': form, 'user': user})

home/views.py
from django.shortcuts import render




def home(request):                                                                                                      #Mostra la pagina iniziale
    user = request.user
    return render(request, "home.html", { 'user': user})

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">                          <!-- Elementi di bootstrap-->
<link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet" type='text/css'>        <!--font per il logo-->

<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
</head>

<body style="background-image:url('/static/images/background.png'); background-size:cover;">
<nav class="navbar navbar-inverse">                                                                                     <!-- barra navigazione -->
    <div class="container-fluid">
        <div class="navbar-header">                                                                                     <!-- logo e bottone menu-->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Bar">                      <!-- bottone menù per quando la pagina è piccola-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                                                                          <!-- 3 linee sul bottone-->
                <span class="icon-bar"></span>
            </button>
            <a style="font-family: 'Indie Flower', cursive;" class="navbar-brand" href="{% url 'home:Home' %}">Ilquadernodellostudente</a>
        </div>
        <div class="collapse navbar-collapse" id="Bar">                                                                 <!-- bottoni che collassano in assenza di spazio-->
            <ul class="nav navbar-nav">
                <li class="active">                                                                                     <!--"illumina" il bottone-->
                    <a href='{% url 'catalog:Search' %}'>
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>                             <!-- icona-->
                        &nbsp;
                        Ricerca avanzata
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'catalog:Itemlist' %}">     <!-- barra di ricerca-->
                {% csrf_token %}
                <input type="text"  placeholder="Cerca un oggetto" class="form-control" name="q">
                <button type="submit" class="btn btn-default">Cerca</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated%}                                                                           <!--Se l'utente è registrato permette di creare una nuova inserzione-->
                    <li class="active">
                        <a href="{% url 'users:Create' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            &nbsp;
                            Nuova inserzione
                        </a>
                    </li>
                {% endif %}
                <li class="active">
                    <a href="{% url 'checkout:Cart' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                        &nbsp;
                        Carrello
                    </a>
                </li>
                {% if user.is_authenticated and user.is_staff%}                                                         <!-- Se l'utente è un admin mostra l'accesso all'amministrazione-->
                    <li class="active">
                        <a href="/admin">
                            <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                            &nbsp;
                            Amministrazione

                        </a>
                    </li>
                {% endif %}
                <li class="active">
                    <a href="{% url 'users:Profile' user.id %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        &nbsp;
                        {% if user.is_authenticated %}                                                                  <!--Se l'utente è registrato mostra il nome del profilo-->
                            {{ user.username }}
                        {% else %}
                            Profilo
                        {% endif %}
                    </a>
                </li>
                {% if user.is_authenticated %}                                                                          <!-- se l'utente è autenticato mostro il bottone per il logout, atrimenti quello per il login-->
                    <li class="active">
                        <a href="{% url 'users:Logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            &nbsp;
                            Logout
                        </a>
                    </li>
                {% else %}
                    <li class="active">
                        <a href="{% url 'users:Login' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            &nbsp;
                            Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>

</html>

templates/deleteitem.html
{% extends "base.html" %}

{% block title %}
    <title>Elimina oggetto</title>
{% endblock %}

{%block body %}
    {% if msg_success %}
        <a href='{% url 'users:Profile' user.id %}' class="btn btn-success btn-lg btn-block" role="button">{{ msg_success }}</a>
    {% else %}
        <div class="row">
            <div class="col-sm-4"></div>       <!-- span di 4 colonne vuote-->
            <div class="col-sm-3">              <!-- 3 colonne centrali-->
                <div  class="thumbnail">
                    <p>Vuoi davvero eliminare l'oggetto?</p>
                    <form  method="post" action=""> <!-- Inoltrato alla stessa pagina-->
                        {% csrf_token %}
                        {{ form.as_p }}   <!-- inserisce i campi del form automaticamente-->
                        <button type="submit" class="btn btn-success">Conferma</button> <a href="javascript:history.back()" class="btn btn-info" role="button">Indietro</a>
                    </form>
                </div>
            </div>
            <div class="col-sm-5"></div>       <!-- span di 5 colonne vuote-->
        </div>

    {% endif %}
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{%block body %}
            <div  class="thumbnail">                                                                                    <!--riquadro-->
                <img  src="/static/images/logo.png" class="img-responsive">
            </div>
        <div class="row">
            <div class="col-sm-6">                                                                                      <!--Pannello a sinistra largo 6 colonne-->
                <div  class="thumbnail">
                    <h3 style="text-align: left;">Benvenuto su Ilquadernodellostudente! Su questo sito hai la possibilità di acquistare o vendere i tuoi appunti scolastici
                        in pochi semplici passaggi. Nel nostro catalogo sono presenti appunti su ogni materia e argomento, con la possibilità di scegliere tra 3 diversi livelli
                        scolastici: medie, superiori e università. Per usufruire a pieno del nostro servizio è obbligatoria la registrazione, ma puoi cominciare subito a cercare se c'è qualcosa che ti interessa
                        nel nostro catalogo grazie alla funzione di
                        <a href='{% url 'catalog:Search' %}'>RICERCA AVANZATA</a></h3>
                </div>
            </div>
            <div class="col-sm-6">                                                                                      <!--Pannello a destra largo 6 colonne-->
                <div  class="thumbnail">
                    {% if user.is_authenticated %}
                        <h3 style="text-align: left;">Hai già eseguito l'accesso al sito! Se vuoi eseguire il logout clicca <a href='{% url 'users:Logout' %}'>QUI</a> </h3>
                    {% else %}
                        <h3 style="text-align: left;">Sembra che tu non abbia ancora fatto il login! Per acquistare o vendere oggetti,lasciare recensioni e comunicare con altri utenti è necessario autenticarsi.
                            Per eseguire il login oppure per creare un nuovo account clicca <a href='{% url 'users:Login' %}'>QUI</a></h3>
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock %}

templates/login-form.html
{% extends "base.html" %}

{% block title %}
    <title>Login</title>
{% endblock %}

{%block body %}
    <div class="row">
        {% if msg_fail or msg_warning %}
            {% if msg_warning %}
                <a href='{% url "home:Home" %}' class="btn btn-warning btn-lg btn-block" role="button">{{ msg_warning}}</a>
            {% endif %}
            {% if msg_fail %}
                <a href="{% url 'users:Login' %}" class="btn btn-danger btn-lg btn-block" role="button">{{ msg_fail }}</a>
            {% endif %}
        {% else %}
            <div class="col-sm-4"></div>       <!-- span di 4 colonne vuote-->
            <div class="col-sm-3">              <!-- 3 colonne centrali-->
                <div  class="thumbnail">
                    <form  method="post" action=""> <!-- Inoltrato alla stessa pagina-->
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit" class="btn btn-success">Esegui Login</button> <a href="javascript:history.back()" class="btn btn-info" role="button">Indietro</a>
                    </form>
                    <p>Non hai un account su Ilquadernodellostudente? <a href='{% url 'users:Signup' %}'>Creane uno!</a></p>
                </div>
            </div>
            <div class="col-sm-5"></div>       <!-- span di 5 colonne vuote-->
        {% endif %}
    </div>
{% endblock %}

templates/selectitem.html
{% extends "base.html" %}

{% block title %}
    <title>Selezione oggetto</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">   <!--Importa il css per le stelle -->
{% endblock %}

{%block body %}
    {% if items %}
        <a href="{% url 'users:Profile' user.id %}" class="btn btn-primary btn-lg btn-block" role="button">Torna al profilo</a>
        <div class="row">
            {% for item in items %}
                <div class="col-sm-3 "> <!--  3 colonne-->
                    <div  class="thumbnail">             <!--contenitore-->
                        <a href="{% url 'catalog:Itemdetail' item.id %}">
                            <img style="height: 300px" src="{{ item.image.url }}" class="img-responsive">          <!-- immagine come link-->
                        </a>
                        <div class="caption">
                            <h2>{{ item.name }}</h2>
                            {% if item.school_level == "U" %}
                                <h4>Livello scolastico: Università</h4>
                            {% elif item.school_level == "S" %}
                                <h4>Livello scolastico: Superiori</h4>
                            {% else %}
                                <h4>Livello scolastico: Medie</h4>
                            {% endif %}
                            <h3>Voto utenti:            {% with voto=vote_list.pop %}
                                {% if voto == 0 %}                                                                     <!-- A seconda del voto inseriamo le stelle corrette-->
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 0.5 %}
                                    <span style="color: orange" class="fa fa-star-half-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 1 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 1.5 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-half-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 2 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 2.5 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-half-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span  class="fa fa-star-o"></span>
                                {% elif voto == 3 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 3.5 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-half-o"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 4 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-o"></span>
                                {% elif voto == 4.5 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star-half-o"></span>
                                {% elif voto == 5 %}
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                    <span style="color: orange" class="fa fa-star checked"></span>
                                {% endif %}
                            {% endwith %}
                                (Votanti:{{ reviews.pop }})
                            </h3>
                            <h3>Prezzo: {{ item.price }}€ </h3>
                            <a href="{% url 'users:Edititem' item.id %}" class="btn btn-primary " role="button">Modifica</a>            <!-- Modifica -->
                            <a href="{% url 'users:Deleteitem' item.id %}" class="btn btn-primary " role="button">Elimina</a>            <!-- Elimina-->
                        </div>
                    </div>
                    <div class="clearfix visible-xs-block"></div>    <!-- aggiusta il resing nel caso di colonne più lungher-->
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}            <!-- non so cosa sia-->
            {% endfor %}
        </div>
    {% else %}
        <a href='{% url 'users:Create' %}' class="btn btn-warning btn-lg btn-block" role="button">Non hai ancora nessun oggetto in vendita, premi questo bottone per creare una nuova inserzione</a>
    {% endif %}
{% endblock %}